trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.azurefunctions_dotnet.json
  - name: analysisProject
    value: AzureFunctions_DotNet

jobs:
  - job: Tests
    pool:
      # TODO: Use generic agents when Azure Functions support .NET 5
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: /OpenWeather

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

  - job: Analysis
    pool:
      # TODO: Use generic agents when Azure Functions support .NET 5
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: build

      - template: '/miscellaneous/build_templates/binskim.yml@templates'
        parameters:
          deleteBinSkim: '**/System.Net.Http.Formatting.dll'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
