trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: AzureFunctions_DotNet

parameters:
  - name: pool
    default: 00-OSIManaged-Containers
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Windows_NT']

jobs:
  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - task: UseDotNet@2
          displayName: 'Install dotnet 6'
          inputs:
            packageType: 'sdk'
            version: '6.x'

        - task: DotNetCoreCLI@2
          displayName: 'Nuget restore'
          inputs:
            command: restore

        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: build

        - template: '/miscellaneous/build_templates/binskim.yml@templates'
          parameters:
            deleteBinSkim: '**/System.Net.Http.Formatting.dll'
            
