trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA

parameters:
  - name: pool
    default: DevOps-Managed-Ubt22-Mdp
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Windows_NT']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    variables:
      - name: CdsTenantId
        value: $(TenantId)
      - name: CdsNamespaceId
        value: $(NamespaceId)
      - name: CdsClientId
        value: $(ClientId)
      - name: CdsClientSecret
        value: $(ClientSecret)
      - name: CdsUri
        value: $(Resource)
    steps:
      - task: UseDotNet@2
        displayName: 'Install dotnet 6'
        inputs:
          packageType: 'sdk'
          version: '6.x'

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, ClientId, ClientSecret, OpenWeatherKey, Resource'

      - task: DotNetCoreCLI@2
        displayName: 'Nuget restore'
        inputs:
          command: restore

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

