trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: AzureFunctions_DotNet

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    variables:
      - name: AdhTenantId
        value: $(TenantId)
      - name: AdhNamespaceId
        value: $(NamespaceId)
      - name: AdhClientId
        value: $(ClientId)
      - name: AdhClientSecret
        value: $(ClientSecret)
      - name: AdhUri
        value: $(Resource)
    steps:
      - task: UseDotNet@2
        displayName: 'Install dotnet 5'
        inputs:
          packageType: 'sdk'
          version: '5.x'

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, ClientId, ClientSecret, OpenWeatherKey, Resource'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - task: UseDotNet@2
          displayName: 'Install dotnet 5'
          inputs:
            packageType: 'sdk'
            version: '5.x'

        - task: DotNetCoreCLI@2
          displayName: 'Nuget restore'
          inputs:
            command: restore

        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: build

        - template: '/miscellaneous/build_templates/binskim.yml@templates'
          parameters:
            deleteBinSkim: '**/System.Net.Http.Formatting.dll'
            
